/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AImage: typeof import('ant-design-vue/es')['Image']
    Archive: typeof import('./src/components/archive/Archive.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    Article: typeof import('./src/components/article/Article.vue')['default']
    ArticleCard: typeof import('./src/components/article/ArticleCard.vue')['default']
    Carousel: typeof import('./src/components/article/Carousel.vue')['default']
    Category: typeof import('./src/components/category/Category.vue')['default']
    CategoryCard: typeof import('./src/components/home/CategoryCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FootBar: typeof import('./src/components/layout/FootBar.vue')['default']
    HeaderCover: typeof import('./src/components/header/HeaderCover.vue')['default']
    HeatMap: typeof import('./src/components/archive/HeatMap.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    HomeCover: typeof import('./src/components/home/HomeCover.vue')['default']
    HomeToolBar: typeof import('./src/components/home/HomeToolBar.vue')['default']
    PieChart: typeof import('./src/components/category/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    Typewriter: typeof import('./src/components/others/Typewriter.vue')['default']
  }
}
