/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    HeaderCover: typeof import('./src/components/others/HeaderCover.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    HomeCover: typeof import('./src/components/home/HomeCover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    Typewriter: typeof import('./src/components/others/Typewriter.vue')['default']
  }
}
